.PHONY: release dev libs clean verify Makefile

release: gen/amalgam/libel1.so gen/amalgam/libel1.a gen/srclib/include/el1/el1.cpp

libs: gen/std/libel1.so gen/std/libel1.a gen/amalgam/libel1.so gen/amalgam/libel1.a gen/srclib/include/el1/el1.cpp

dev: gen/std/link-test-so gen/std/gtests
	LD_LIBRARY_PATH=gen/std ./gen/std/link-test-so
	LD_LIBRARY_PATH=gen/std ./gen/std/gtests

gen/std/libel1.so: gen/std/db_postgres.o gen/std/debug.o gen/std/dev_dht22.o gen/std/dev_gpio_bcm283x.o gen/std/dev_gpio.o gen/std/dev_gpio_hd44780.o gen/std/dev_gpio_hd44780.data.o gen/std/dev_gpio_native.linux.o gen/std/dev_i2c.o gen/std/dev_i2c_mpu6050.o gen/std/dev_i2c_native.linux.o gen/std/dev_i2c_opt3001.o gen/std/dev_i2c_pca9555.o gen/std/dev_spi_hx711.o gen/std/dev_spi_native.linux.o gen/std/dev_spi_w1bb.o gen/std/dev_w1.o gen/std/dev_w1_ds18x20.o gen/std/error.o gen/std/error.posix.o gen/std/io_collection_map.o gen/std/io_file.o gen/std/io_file.linux.o gen/std/io_file.posix.o gen/std/io_format_base64.o gen/std/io_format_json.o gen/std/io_net_http.o gen/std/io_net_ip.o gen/std/io_net_ip.posix.o gen/std/io_stream.o gen/std/io_stream.linux.o gen/std/io_text.o gen/std/io_text_encoding.o gen/std/io_text_encoding_utf8.o gen/std/io_text_string.o gen/std/io_text_string.data.o gen/std/io_text_terminal.posix.o gen/std/system_cmdline.o gen/std/system_handle.posix.o gen/std/system_memory.linux.o gen/std/system_random.o gen/std/system_random.linux.o gen/std/system_task.o gen/std/system_task.linux.aarch64.o gen/std/system_task.linux.arm32.o gen/std/system_task.linux.o gen/std/system_task.linux.x64.o gen/std/system_task.posix.o gen/std/system_time.o gen/std/system_time.posix.o gen/std/system_time_timer.o gen/std/system_time_timer.linux.o gen/std/system_time.windows.o gen/std/system_waitable.o gen/std/util_bits.o gen/std/include
	mkdir -p gen/std
	'/bin/g++' gen/std/db_postgres.o gen/std/debug.o gen/std/dev_dht22.o gen/std/dev_gpio_bcm283x.o gen/std/dev_gpio.o gen/std/dev_gpio_hd44780.o gen/std/dev_gpio_hd44780.data.o gen/std/dev_gpio_native.linux.o gen/std/dev_i2c.o gen/std/dev_i2c_mpu6050.o gen/std/dev_i2c_native.linux.o gen/std/dev_i2c_opt3001.o gen/std/dev_i2c_pca9555.o gen/std/dev_spi_hx711.o gen/std/dev_spi_native.linux.o gen/std/dev_spi_w1bb.o gen/std/dev_w1.o gen/std/dev_w1_ds18x20.o gen/std/error.o gen/std/error.posix.o gen/std/io_collection_map.o gen/std/io_file.o gen/std/io_file.linux.o gen/std/io_file.posix.o gen/std/io_format_base64.o gen/std/io_format_json.o gen/std/io_net_http.o gen/std/io_net_ip.o gen/std/io_net_ip.posix.o gen/std/io_stream.o gen/std/io_stream.linux.o gen/std/io_text.o gen/std/io_text_encoding.o gen/std/io_text_encoding_utf8.o gen/std/io_text_string.o gen/std/io_text_string.data.o gen/std/io_text_terminal.posix.o gen/std/system_cmdline.o gen/std/system_handle.posix.o gen/std/system_memory.linux.o gen/std/system_random.o gen/std/system_random.linux.o gen/std/system_task.o gen/std/system_task.linux.aarch64.o gen/std/system_task.linux.arm32.o gen/std/system_task.linux.o gen/std/system_task.linux.x64.o gen/std/system_task.posix.o gen/std/system_time.o gen/std/system_time.posix.o gen/std/system_time_timer.o gen/std/system_time_timer.linux.o gen/std/system_time.windows.o gen/std/system_waitable.o gen/std/util_bits.o -o gen/std/libel1.so '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-shared' -I gen/std/include

gen/std/libel1.a: gen/std/db_postgres.o gen/std/debug.o gen/std/dev_dht22.o gen/std/dev_gpio_bcm283x.o gen/std/dev_gpio.o gen/std/dev_gpio_hd44780.o gen/std/dev_gpio_hd44780.data.o gen/std/dev_gpio_native.linux.o gen/std/dev_i2c.o gen/std/dev_i2c_mpu6050.o gen/std/dev_i2c_native.linux.o gen/std/dev_i2c_opt3001.o gen/std/dev_i2c_pca9555.o gen/std/dev_spi_hx711.o gen/std/dev_spi_native.linux.o gen/std/dev_spi_w1bb.o gen/std/dev_w1.o gen/std/dev_w1_ds18x20.o gen/std/error.o gen/std/error.posix.o gen/std/io_collection_map.o gen/std/io_file.o gen/std/io_file.linux.o gen/std/io_file.posix.o gen/std/io_format_base64.o gen/std/io_format_json.o gen/std/io_net_http.o gen/std/io_net_ip.o gen/std/io_net_ip.posix.o gen/std/io_stream.o gen/std/io_stream.linux.o gen/std/io_text.o gen/std/io_text_encoding.o gen/std/io_text_encoding_utf8.o gen/std/io_text_string.o gen/std/io_text_string.data.o gen/std/io_text_terminal.posix.o gen/std/system_cmdline.o gen/std/system_handle.posix.o gen/std/system_memory.linux.o gen/std/system_random.o gen/std/system_random.linux.o gen/std/system_task.o gen/std/system_task.linux.aarch64.o gen/std/system_task.linux.arm32.o gen/std/system_task.linux.o gen/std/system_task.linux.x64.o gen/std/system_task.posix.o gen/std/system_time.o gen/std/system_time.posix.o gen/std/system_time_timer.o gen/std/system_time_timer.linux.o gen/std/system_time.windows.o gen/std/system_waitable.o gen/std/util_bits.o gen/std/include
	mkdir -p gen/std
	ar rcs gen/std/libel1.a gen/std/db_postgres.o gen/std/debug.o gen/std/dev_dht22.o gen/std/dev_gpio_bcm283x.o gen/std/dev_gpio.o gen/std/dev_gpio_hd44780.o gen/std/dev_gpio_hd44780.data.o gen/std/dev_gpio_native.linux.o gen/std/dev_i2c.o gen/std/dev_i2c_mpu6050.o gen/std/dev_i2c_native.linux.o gen/std/dev_i2c_opt3001.o gen/std/dev_i2c_pca9555.o gen/std/dev_spi_hx711.o gen/std/dev_spi_native.linux.o gen/std/dev_spi_w1bb.o gen/std/dev_w1.o gen/std/dev_w1_ds18x20.o gen/std/error.o gen/std/error.posix.o gen/std/io_collection_map.o gen/std/io_file.o gen/std/io_file.linux.o gen/std/io_file.posix.o gen/std/io_format_base64.o gen/std/io_format_json.o gen/std/io_net_http.o gen/std/io_net_ip.o gen/std/io_net_ip.posix.o gen/std/io_stream.o gen/std/io_stream.linux.o gen/std/io_text.o gen/std/io_text_encoding.o gen/std/io_text_encoding_utf8.o gen/std/io_text_string.o gen/std/io_text_string.data.o gen/std/io_text_terminal.posix.o gen/std/system_cmdline.o gen/std/system_handle.posix.o gen/std/system_memory.linux.o gen/std/system_random.o gen/std/system_random.linux.o gen/std/system_task.o gen/std/system_task.linux.aarch64.o gen/std/system_task.linux.arm32.o gen/std/system_task.linux.o gen/std/system_task.linux.x64.o gen/std/system_task.posix.o gen/std/system_time.o gen/std/system_time.posix.o gen/std/system_time_timer.o gen/std/system_time_timer.linux.o gen/std/system_time.windows.o gen/std/system_waitable.o gen/std/util_bits.o

gen/std/link-test-so: gen/std/libel1.so gen/std/include
	'/bin/g++' support/link-test.cpp -o gen/std/link-test-so '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -L gen/std -l el1 -I gen/std/include

gen/std/link-test-a: gen/std/libel1.a gen/std/include
	'/bin/g++' support/link-test.cpp gen/std/libel1.a -o gen/std/link-test-a '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -I gen/std/include

gen/amalgam/el1.o: gen/srclib/include/el1/el1.cpp
	mkdir -p gen/amalgam
	'/bin/g++' gen/srclib/include/el1/el1.cpp -o gen/amalgam/el1.o -c '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' -I gen/srclib/include

gen/amalgam/libel1.so: gen/amalgam/el1.o gen/amalgam/include
	'/bin/g++' gen/amalgam/el1.o -o gen/amalgam/libel1.so '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-shared'

gen/amalgam/libel1.a: gen/amalgam/el1.o gen/amalgam/include
	mkdir -p gen/amalgam
	ar rcs gen/amalgam/libel1.a gen/amalgam/el1.o

gen/amalgam/link-test-so: gen/amalgam/libel1.so
	'/bin/g++' support/link-test.cpp -o gen/amalgam/link-test-so '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -L gen/amalgam -l el1 -I gen/amalgam/include

gen/amalgam/link-test-a: gen/amalgam/libel1.a
	'/bin/g++' support/link-test.cpp gen/amalgam/libel1.a -o gen/amalgam/link-test-a '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -I gen/amalgam/include

gen/srclib/include/el1/el1.cpp: src/el1/db_postgres.cpp src/el1/debug.cpp src/el1/dev_dht22.cpp src/el1/dev_gpio_bcm283x.cpp src/el1/dev_gpio.cpp src/el1/dev_gpio_hd44780.cpp src/el1/dev_gpio_hd44780.data.cpp src/el1/dev_gpio_native.linux.cpp src/el1/dev_i2c.cpp src/el1/dev_i2c_mpu6050.cpp src/el1/dev_i2c_native.linux.cpp src/el1/dev_i2c_opt3001.cpp src/el1/dev_i2c_pca9555.cpp src/el1/dev_spi_hx711.cpp src/el1/dev_spi_native.linux.cpp src/el1/dev_spi_w1bb.cpp src/el1/dev_w1.cpp src/el1/dev_w1_ds18x20.cpp src/el1/error.cpp src/el1/error.posix.cpp src/el1/io_collection_map.cpp src/el1/io_file.cpp src/el1/io_file.linux.cpp src/el1/io_file.posix.cpp src/el1/io_format_base64.cpp src/el1/io_format_json.cpp src/el1/io_net_http.cpp src/el1/io_net_ip.cpp src/el1/io_net_ip.posix.cpp src/el1/io_stream.cpp src/el1/io_stream.linux.cpp src/el1/io_text.cpp src/el1/io_text_encoding.cpp src/el1/io_text_encoding_utf8.cpp src/el1/io_text_string.cpp src/el1/io_text_string.data.cpp src/el1/io_text_terminal.posix.cpp src/el1/system_cmdline.cpp src/el1/system_handle.posix.cpp src/el1/system_memory.linux.cpp src/el1/system_random.cpp src/el1/system_random.linux.cpp src/el1/system_task.cpp src/el1/system_task.linux.aarch64.cpp src/el1/system_task.linux.arm32.cpp src/el1/system_task.linux.cpp src/el1/system_task.linux.x64.cpp src/el1/system_task.posix.cpp src/el1/system_time.cpp src/el1/system_time.posix.cpp src/el1/system_time_timer.cpp src/el1/system_time_timer.linux.cpp src/el1/system_time.windows.cpp src/el1/system_waitable.cpp src/el1/util_bits.cpp src/el1/db.hpp src/el1/db_postgres.hpp src/el1/debug.hpp src/el1/def.hpp src/el1/dev_dht22.hpp src/el1/dev_gpio_bcm283x.hpp src/el1/dev_gpio_hd44780.hpp src/el1/dev_gpio.hpp src/el1/dev_gpio_native.hpp src/el1/dev_i2c.hpp src/el1/dev_i2c_mpu6050.hpp src/el1/dev_i2c_native.hpp src/el1/dev_i2c_opt3001.hpp src/el1/dev_i2c_pca9555.hpp src/el1/dev_spi.hpp src/el1/dev_spi_hx711.hpp src/el1/dev_spi_native.hpp src/el1/dev_spi_w1bb.hpp src/el1/dev_w1_ds18x20.hpp src/el1/dev_w1.hpp src/el1/error.hpp src/el1/io_collection_list.hpp src/el1/io_collection_map.hpp src/el1/io_file.hpp src/el1/io_format_base64.hpp src/el1/io_format_json.hpp src/el1/io_net_http.hpp src/el1/io_net_ip.hpp src/el1/io_serialization.hpp src/el1/io_stream_fifo.hpp src/el1/io_stream.hpp src/el1/io_stream_producer.hpp src/el1/io_text_encoding.hpp src/el1/io_text_encoding_utf8.hpp src/el1/io_text.hpp src/el1/io_text_string.hpp src/el1/io_text_terminal.hpp src/el1/io_types.hpp src/el1/math.hpp src/el1/system_cmdline.hpp src/el1/system_handle.hpp src/el1/system_memory.hpp src/el1/system_random.hpp src/el1/system_task.hpp src/el1/system_time.hpp src/el1/system_time_timer.hpp src/el1/system_waitable.hpp src/el1/util_bits.hpp src/el1/util_event.hpp src/el1/util_function.hpp src/el1/util.hpp src/el1/wip_dev_sensor.hpp support/generate-srclib.sh
	./support/generate-srclib.sh

gen/srclib/link-test: gen/include gen/srclib/include/el1/el1.cpp
	'/bin/g++' support/link-test.cpp -o gen/srclib/link-test '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -I gen/srclib/include

gen/std/include: src/el1 support/generate-include-dir.sh src/el1/db.hpp src/el1/db_postgres.hpp src/el1/debug.hpp src/el1/def.hpp src/el1/dev_dht22.hpp src/el1/dev_gpio_bcm283x.hpp src/el1/dev_gpio_hd44780.hpp src/el1/dev_gpio.hpp src/el1/dev_gpio_native.hpp src/el1/dev_i2c.hpp src/el1/dev_i2c_mpu6050.hpp src/el1/dev_i2c_native.hpp src/el1/dev_i2c_opt3001.hpp src/el1/dev_i2c_pca9555.hpp src/el1/dev_spi.hpp src/el1/dev_spi_hx711.hpp src/el1/dev_spi_native.hpp src/el1/dev_spi_w1bb.hpp src/el1/dev_w1_ds18x20.hpp src/el1/dev_w1.hpp src/el1/error.hpp src/el1/io_collection_list.hpp src/el1/io_collection_map.hpp src/el1/io_file.hpp src/el1/io_format_base64.hpp src/el1/io_format_json.hpp src/el1/io_net_http.hpp src/el1/io_net_ip.hpp src/el1/io_serialization.hpp src/el1/io_stream_fifo.hpp src/el1/io_stream.hpp src/el1/io_stream_producer.hpp src/el1/io_text_encoding.hpp src/el1/io_text_encoding_utf8.hpp src/el1/io_text.hpp src/el1/io_text_string.hpp src/el1/io_text_terminal.hpp src/el1/io_types.hpp src/el1/math.hpp src/el1/system_cmdline.hpp src/el1/system_handle.hpp src/el1/system_memory.hpp src/el1/system_random.hpp src/el1/system_task.hpp src/el1/system_time.hpp src/el1/system_time_timer.hpp src/el1/system_waitable.hpp src/el1/util_bits.hpp src/el1/util_event.hpp src/el1/util_function.hpp src/el1/util.hpp src/el1/wip_dev_sensor.hpp
	./support/generate-include-dir.sh gen/std/include

gen/amalgam/include: src/el1 support/generate-include-dir.sh src/el1/db.hpp src/el1/db_postgres.hpp src/el1/debug.hpp src/el1/def.hpp src/el1/dev_dht22.hpp src/el1/dev_gpio_bcm283x.hpp src/el1/dev_gpio_hd44780.hpp src/el1/dev_gpio.hpp src/el1/dev_gpio_native.hpp src/el1/dev_i2c.hpp src/el1/dev_i2c_mpu6050.hpp src/el1/dev_i2c_native.hpp src/el1/dev_i2c_opt3001.hpp src/el1/dev_i2c_pca9555.hpp src/el1/dev_spi.hpp src/el1/dev_spi_hx711.hpp src/el1/dev_spi_native.hpp src/el1/dev_spi_w1bb.hpp src/el1/dev_w1_ds18x20.hpp src/el1/dev_w1.hpp src/el1/error.hpp src/el1/io_collection_list.hpp src/el1/io_collection_map.hpp src/el1/io_file.hpp src/el1/io_format_base64.hpp src/el1/io_format_json.hpp src/el1/io_net_http.hpp src/el1/io_net_ip.hpp src/el1/io_serialization.hpp src/el1/io_stream_fifo.hpp src/el1/io_stream.hpp src/el1/io_stream_producer.hpp src/el1/io_text_encoding.hpp src/el1/io_text_encoding_utf8.hpp src/el1/io_text.hpp src/el1/io_text_string.hpp src/el1/io_text_terminal.hpp src/el1/io_types.hpp src/el1/math.hpp src/el1/system_cmdline.hpp src/el1/system_handle.hpp src/el1/system_memory.hpp src/el1/system_random.hpp src/el1/system_task.hpp src/el1/system_time.hpp src/el1/system_time_timer.hpp src/el1/system_waitable.hpp src/el1/util_bits.hpp src/el1/util_event.hpp src/el1/util_function.hpp src/el1/util.hpp src/el1/wip_dev_sensor.hpp
	./support/generate-include-dir.sh gen/amalgam/include

gen/testdata: support/generate-testdata.sh $(wildcard testdata/*)
	./support/generate-testdata.sh

gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a &: submodules/googletest
	set -eu; export CXX='/bin/g++'; export CC='/bin/gcc'; mkdir -p gen/gtest; cd gen/gtest; cmake ../../submodules/googletest; make

gen/srclib/gtests: gen/srclib/include/el1/el1.cpp $(wildcard src/el1/test/*.cpp) gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a
	'/bin/g++' src/el1/test/*.cpp gen/srclib/include/el1/el1.cpp gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a -o gen/srclib/gtests '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -I gen/srclib/include

gen/std/gtests: gen/std/include gen/testdata gen/std/libel1.so $(wildcard src/el1/test/*.cpp) gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a
	'/bin/g++' src/el1/test/*.cpp gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a -o gen/std/gtests '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -I gen/std/include -L gen/std -l el1

gen/amalgam/gtests: gen/amalgam/include gen/testdata gen/amalgam/libel1.a $(wildcard src/el1/test/*.cpp) gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a
	'/bin/g++' src/el1/test/*.cpp gen/amalgam/libel1.a gen/gtest/lib/libgtest.a gen/gtest/lib/libgtest_main.a -o gen/amalgam/gtests '-DEL1_WITH_POSTGRES' '-DEL1_WITH_VALGRIND' '-ftemplate-depth=50' '-fPIC' '-fdiagnostics-color=always' '-Wall' '-Wextra' '-Werror' '-Wno-unused-parameter' '-Wno-error=unused-function' '-I' 'submodules/googletest/googletest/include' '-std=gnu++20' '-Wno-unused-const-variable' '-I/usr/include/pgsql' '-DOPENSSL_LOAD_CONF' '-L/usr/lib/postgresql15/lib64' '-lpq' '-pthread' -I gen/amalgam/include

link-tests: gen/std/link-test-a gen/amalgam/link-test-a gen/std/link-test-so gen/amalgam/link-test-so
	./gen/std/link-test-a
	./gen/amalgam/link-test-a
	LD_LIBRARY_PATH=gen/std ./gen/std/link-test-so
	LD_LIBRARY_PATH=gen/amalgam ./gen/amalgam/link-test-so

unit-tests: gen/std/gtests gen/amalgam/gtests gen/srclib/gtests
	./gen/std/gtests
	./gen/amalgam/gtests
	./gen/srclib/gtests

verify: link-tests unit-tests

Makefile:
	./support/generate-makefile.sh

clean:
	rm --recursive --force -- gen

include  src/el1/db_postgres.Makefile src/el1/debug.Makefile src/el1/dev_dht22.Makefile src/el1/dev_gpio_bcm283x.Makefile src/el1/dev_gpio.Makefile src/el1/dev_gpio_hd44780.Makefile src/el1/dev_gpio_hd44780.data.Makefile src/el1/dev_gpio_native.linux.Makefile src/el1/dev_i2c.Makefile src/el1/dev_i2c_mpu6050.Makefile src/el1/dev_i2c_native.linux.Makefile src/el1/dev_i2c_opt3001.Makefile src/el1/dev_i2c_pca9555.Makefile src/el1/dev_spi_hx711.Makefile src/el1/dev_spi_native.linux.Makefile src/el1/dev_spi_w1bb.Makefile src/el1/dev_w1.Makefile src/el1/dev_w1_ds18x20.Makefile src/el1/error.Makefile src/el1/error.posix.Makefile src/el1/io_collection_map.Makefile src/el1/io_file.Makefile src/el1/io_file.linux.Makefile src/el1/io_file.posix.Makefile src/el1/io_format_base64.Makefile src/el1/io_format_json.Makefile src/el1/io_net_http.Makefile src/el1/io_net_ip.Makefile src/el1/io_net_ip.posix.Makefile src/el1/io_stream.Makefile src/el1/io_stream.linux.Makefile src/el1/io_text.Makefile src/el1/io_text_encoding.Makefile src/el1/io_text_encoding_utf8.Makefile src/el1/io_text_string.Makefile src/el1/io_text_string.data.Makefile src/el1/io_text_terminal.posix.Makefile src/el1/system_cmdline.Makefile src/el1/system_handle.posix.Makefile src/el1/system_memory.linux.Makefile src/el1/system_random.Makefile src/el1/system_random.linux.Makefile src/el1/system_task.Makefile src/el1/system_task.linux.aarch64.Makefile src/el1/system_task.linux.arm32.Makefile src/el1/system_task.linux.Makefile src/el1/system_task.linux.x64.Makefile src/el1/system_task.posix.Makefile src/el1/system_time.Makefile src/el1/system_time.posix.Makefile src/el1/system_time_timer.Makefile src/el1/system_time_timer.linux.Makefile src/el1/system_time.windows.Makefile src/el1/system_waitable.Makefile src/el1/util_bits.Makefile
