#pragma once

#include "dev_spi.hpp"
#include "io_collection_list.hpp"
#include "io_stream.hpp"
#include "system_time_timer.hpp"

namespace el1::dev::spi::si446x
{
	using namespace io::types;
	using io::collection::list::array_t;

	static const u32_t HZ_CLOCK_SPI_MAX = 10000000;
	static const u32_t HZ_CLOCK_SPI_DEFAULT = 1000000;
	static const usys_t N_COMMAND_BYTES_MAX = 16;
	static const usys_t N_RESPONSE_BYTES_MAX = 16;

	enum class ECommand : byte_t
	{
		NOP = 0x00,
		PART_INFO = 0x01,
		POWER_UP = 0x02,
		FUNC_INFO = 0x10,
		SET_PROPERTY = 0x11,
		GET_PROPERTY = 0x12,
		GPIO_PIN_CFG = 0x13,
		FIFO_INFO = 0x15,
		GET_INT_STATUS = 0x20,
		GET_PH_STATUS = 0x21,
		GET_MODEM_STATUS = 0x22,
		GET_CHIP_STATUS = 0x23,
		START_TX = 0x31,
		START_RX = 0x32,
		REQUEST_DEVICE_STATE = 0x33,
		CHANGE_STATE = 0x34,
		READ_CMD_BUFF = 0x44,
		WRITE_TX_FIFO = 0x66,
		READ_RX_FIFO = 0x77
	};

	// Configuration record stream as generated by Silicon Labs WDS/radio_config.h:
	// one length byte followed by that many command bytes, terminated by length 0.
	// Keeping this format intact also permits WDS patch records before POWER_UP.
	struct TConfiguration
	{
		const array_t<const byte_t> data;

		constexpr explicit TConfiguration(const array_t<const byte_t> data) : data(data) {}

		template<usys_t N>
		constexpr explicit TConfiguration(const byte_t (&data)[N]) : data(data, N) {}
	};

	struct TPartInfo
	{
		byte_t chip_revision;
		u16_t part;
		byte_t part_build;
		u16_t id;
		byte_t customer;
		byte_t rom_id;
	};

	struct TFifoInfo
	{
		byte_t rx_count;
		byte_t tx_space;
	};

	struct TDeviceState
	{
		byte_t state;
		byte_t channel;
	};

	struct TInterruptStatus
	{
		byte_t interrupt_pending;
		byte_t interrupt_status;
		byte_t packet_handler_pending;
		byte_t packet_handler_status;
		byte_t modem_pending;
		byte_t modem_status;
		byte_t chip_pending;
		byte_t chip_status;

		bool AnyPending() const
		{
			return interrupt_pending != 0 || packet_handler_pending != 0 || modem_pending != 0 || chip_pending != 0;
		}
	};

	class TRadio : public io::stream::ISource<TInterruptStatus>
	{
		protected:
			std::unique_ptr<ISpiDevice> device;
			std::unique_ptr<gpio::IPin> shutdown;
			std::unique_ptr<gpio::IPin> irq;
			system::time::timer::TTimer poll_timer;
			const system::time::TTime command_timeout;
			const system::time::TTime poll_interval;
			bool is_shutdown;

			bool ReadCommandResponse(byte_t* response, const usys_t n_response_bytes, const system::time::TTime timeout);

		public:
			void Shutdown(const bool shutdown);
			void Reset();

			bool CommandReady();
			void WaitCommandReady(const system::time::TTime timeout = -1);
			void SendCommand(const array_t<const byte_t> command);
			void SendCommandGetResponse(const array_t<const byte_t> command, byte_t* response, const usys_t n_response_bytes);

			void LoadConfiguration(const TConfiguration& configuration);
			void LoadConfiguration(io::stream::ISource<byte_t>& source);

			// Reset and replay a complete WDS configuration stream. This intentionally does not
			// issue POWER_UP on its own because WDS patch records may have to precede POWER_UP.
			void Initialize(const TConfiguration& configuration);
			void Initialize(io::stream::ISource<byte_t>& source);

			void PowerUp(const u32_t xo_frequency_hz, const byte_t boot_options = 0x01, const byte_t xtal_options = 0x00);
			TPartInfo PartInfo();
			TDeviceState DeviceState();
			void ChangeState(const byte_t state);

			void SetProperties(const byte_t group, const byte_t start_property, const array_t<const byte_t> values);
			void GetProperties(const byte_t group, const byte_t start_property, array_t<byte_t> values);

			TFifoInfo FifoInfo(const byte_t reset_flags = 0x00);
			void ReadRxFifo(array_t<byte_t> data);
			void WriteTxFifo(const array_t<const byte_t> data);
			void StartTx(const byte_t channel, const u16_t length, const byte_t condition = 0x00);
			void StartRx(const byte_t channel, const u16_t length = 0, const byte_t condition = 0x00, const byte_t next_state_on_timeout = 0x00, const byte_t next_state_on_valid_packet = 0x00, const byte_t next_state_on_invalid_packet = 0x00);

			TInterruptStatus InterruptStatus(const byte_t packet_handler_clear_mask = 0x00, const byte_t modem_clear_mask = 0x00, const byte_t chip_clear_mask = 0x00);

			// The radio is an interrupt event stream. With nIRQ connected, OnInputReady() is the
			// GPIO waitable; without nIRQ a timer waitable provides a polling fallback.
			usys_t Read(TInterruptStatus* const events, const usys_t n_events_max) final override EL_WARN_UNUSED_RESULT;
			const system::waitable::IWaitable* OnInputReady() const final override;

			TRadio(
				std::unique_ptr<ISpiDevice> device,
				std::unique_ptr<gpio::IPin> shutdown,
				std::unique_ptr<gpio::IPin> irq = nullptr,
				const u32_t hz_clock = HZ_CLOCK_SPI_DEFAULT,
				const system::time::TTime command_timeout = 1.0,
				const system::time::TTime poll_interval = 0.005
			);
	};
}
